version: "3"

services:
  consul:
    image: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - demo-net

  product-service:
    build:
      context: ..
      dockerfile: product-service/Dockerfile
    image: somkiat/product-service:1.0
    environment:
      - PRODUCT_SERVICE_PORT=8100
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "8100:8100"
    depends_on:
      - consul
    networks:
      - demo-net

  user-service:
    build:
      context: ..
      dockerfile: user-service/Dockerfile
    image: somkiat/user-service:1.0
    environment:
      - USER_SERVICE_PORT=8080
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "8080:8080"
    depends_on:
      - consul
    networks:
      - demo-net

  user-service-docker:
    build:
      context: ..
      dockerfile: user-service-docker/Dockerfile
    image: somkiat/user-service-docker:1.0
    environment:
      - USER_SERVICE_PORT=8081
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "8081:8081"
    depends_on:
      - consul
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge
