scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["192.168.1.105:8080"]
        labels:
          service: "beer-service"
          group: "production"
